name: "Pull Request Labeler"
on:
    pull_request_target:
        types:
            - closed

jobs:
  merged:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        perl .github/bin/labeler ${{ github.event.number }} remove
        perl .github/bin/labeler ${{ github.event.number }} add 'Status: accepted'
  rejected:
    if: github.event.pull_request.merged == false
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        perl .github/bin/labeler ${{ github.event.number }} remove
        perl .github/bin/labeler ${{ github.event.number }} add 'Status: rejected'
