---
name: test-perlreview-images

permissions:
    actions: write
    contents: read

on:
    workflow_dispatch:

jobs:
    perl:
        environment: automated_testing
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                perl-version:
                    - '5.40'
        container:
            image: perlreview/${{ matrix.perl-version }}-modules
        steps:
            - uses: actions/checkout@v3
            - name: git corrections
              run: |
                git config --global --add safe.directory "$(pwd)"
            - name: Platform check
              run: uname -a
            - name: Perl version check
              run: |
                perl -V
                perl -v | perl -0777 -ne 'm/(v5\.\d+)/ && print "PERL_VERSION=$1"' >> $GITHUB_ENV
